name: xharbour for Windows 64 

on:
  push:
    paths: 
      - '.github/workflows/win_msvc64.yml'

jobs:
  build:
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Checkout xharbour repo
        uses: actions/checkout@v2
        with:
          repository: pcordonet/xharbour
          path: xharbour
         
      - name: Build xharbour
        working-directory: xharbour
        shell: cmd
        run: |
          call make_vc.bat

      - name: Prepare artifact
        shell: cmd
        run: |
          mkdir artifact
          mkdir artifact\Samples
          dir xharbour\bin
