name: xharbour for Windows 64 

on:
  push:
    paths: 
      - '.github/workflows/win_msvc64.yml'

jobs:
  build:
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v2
    
      - name: Checkout xharbour repo
        uses: actions/checkout@v2
        with:
          repository: pcordonet/xharbour
          path: xharbour
         
      - name: Build xharbour
        working-directory: xharbour
        shell: cmd
        run: |
          call make_vc.bat

      - name: Prepare artifact
        shell: cmd
        run: |
          mkdir artifact
          mkdir artifact\Samples
          xcopy harbour\contrib\mod_harbour.v2\Samples\*.* .\artifact\Samples /E /H /C /I
          xcopy harbour\contrib\mod_harbour.v2\output\win64\mod_harbour.v2.so .\artifact /E /H /C /I

      - name: Upload mod_harbour.v2.so/libmhapache.dll/Samples to artifact
        uses: actions/upload-artifact@v2
        with:
          name: mod_harbour.v2_win64
          path: artifact
